### ISSUE TITLE
not able to edit 'Content' in the existing wiki pages

### ISSUE THREAD

**Issue by saru2020** [frappe/wiki#81] opened 2022-04-27 08:06 UTC
not able to edit 'Content' in the existing wiki pages after pulling the source from the master branch.

note: I was able to do so earlier 2-3 months back, not sure which commit or branch I should point to.

note: I'm able to edit title & route

am I missing anything?

**Comment by saru2020** [comment] 2022-04-27 08:42
update: 
via doctype: not able to edit
via wiki app: I'm able to edit via 'Rich Text' option, but not able to edit via 'Markdown' option

**Comment by saru2020** [comment] 2022-04-27 10:24
via doctype edit issue: i noticed that the textarea size is 1px for both height & width.

to get rid of this issue, which branch/tag/version should I use?

**Comment by saru2020** [comment] 2022-04-27 14:09
one more update:
tried using 'version-13' with frappe v14, and I'm able to edit the content but not able to see the wiki page, seeing these errors:
> "GET /assets/wiki/css/wiki.css HTTP/1.1" 404 -
> "GET /assets/wiki/js/wiki.min.js HTTP/1.1" 404 -

not sure, what I'm doing is correct. 

any inputs?

**Comment by saru2020** [comment] 2022-04-28 19:51
got to update the links in the documentation via doctype by inspecting and enabling focus on the textarea
note: this is a hack and the issue still has to be fixed

**Comment by hasnain2808** [comment] 2022-07-23 16:21
The develop branch of wiki works with develop of frappe
This is how docs.erpnext.com is also setup

**Comment by BreadGenie** [comment] 2023-01-11 16:09
Closing this since we can't reproduce it with the latest commit from develop branch

**Closed by BreadGenie** 2023-01-11 16:09 UTC
