### ISSUE TITLE
Wiki not showing in workspace, Public option is grayed out.

### ISSUE THREAD

**Issue by TheTechnologyStudio** [frappe/wiki#128] opened 2023-03-19 23:54 UTC
Hello, I installed Frappe Wiki and Frappe Tickets to a new site on my frappe installation and i can search the apps on the dashboard but the apps are missing in the left menus. See pictures attached.

it does not seem to exist on non desk view also.

Any help would be amazing. Thank you.

![Screenshot_168](https://user-images.githubusercontent.com/19619093/226217763-dae28db3-8957-408e-a307-d729b44cae42.png)
![Screenshot_169](https://user-images.githubusercontent.com/19619093/226217765-4285bb1a-b504-4f97-9eaa-a3026471f177.png)
![Screenshot_170](https://user-images.githubusercontent.com/19619093/226217767-dfea7c96-c1cf-459b-b336-6c846842e388.png)
![Screenshot_171](https://user-images.githubusercontent.com/19619093/226217768-2242ddf0-01e3-46a1-bbda-fd94842cb72c.png)

**Comment by BreadGenie** [comment] 2023-04-02 07:21
Duplicate of #85

**Closed by BreadGenie** 2023-04-02 07:21 UTC
