### ISSUE TITLE
ModuleNotFoundError: No module named 'redis.commands'

### ISSUE THREAD

**Issue by redolencetech** [frappe/wiki#153] opened 2023-05-07 14:24 UTC
I'm trying to install Wiki onto my v14 ERPNext installation (Ubuntu VM), trying to install it gives me the above error

My install script:
```
pip install redis==3.5.3
bench get-app https://github.com/frappe/wiki --resolve-deps
bench --site erpnext install-app wiki
```

Output:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/6630615/236683396-ec4d16d9-9189-419e-8ca3-e55d7714bfcf.png">

**Comment by BreadGenie** [comment] 2023-05-07 14:34
You'll have to use `redisearch-v14` temporarily instead of `version-14` or `master` until #148 is merged.

Also duplicate of #145

**Closed by BreadGenie** 2023-05-07 14:34 UTC
