### ISSUE TITLE
Search on wiki pages is not working

### ISSUE THREAD

**Issue by parameshnalla** [frappe/wiki#119] opened 2023-01-25 05:08 UTC
While testing the wiki pages found that the 
![Screen Shot 2023-01-25 at 12 08 42 AM](https://user-images.githubusercontent.com/7420632/214484760-1b4734ff-9e28-4111-af12-adc6c6902f5a.png)
search bar is not working. It is not able to find any matches in the current page itself.

**Comment by BreadGenie** [comment] 2023-01-25 05:16
Can you try the workaround in #57?
Closing this issue since it's the duplicate of #57.

**Closed by BreadGenie** 2023-01-25 05:16 UTC
